platform :ios,'8.4'

abstract_target 'main' do
    pod 'RegexKitLite'
    pod 'UIImage+animatedGif'
    pod 'Google-Mobile-Ads-SDK'
    pod 'SFHFKeychainUtils'
    pod 'TTTAttributedLabel'

    target 'Illustail'
    target 'Pixitail'
end

abstract_target 'widget' do
    pod 'RegexKitLite'
    
    target 'Illustail_Widget'
    target 'Pixitail_Widget'
end

